# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='N/A', max_length=100, verbose_name='User')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('time_in', models.DateTimeField(auto_now_add=True, verbose_name='Time In')),
                ('time_out', models.DateTimeField(auto_now_add=True, verbose_name='Time Out')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
