# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0002_auto_20170523_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='duration',
        ),
        migrations.AddField(
            model_name='work',
            name='active_session',
            field=models.BooleanField(default=True, verbose_name='Active Session'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 23, 14, 47, 12, 253389, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 23, 14, 47, 12, 253625, tzinfo=utc), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 23, 14, 47, 12, 253663, tzinfo=utc), verbose_name='Time Out'),
        ),
    ]
