# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0007_auto_20170523_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(default=None, max_length=50, verbose_name='First Name')),
                ('MName', models.CharField(default=None, max_length=50, verbose_name='Middle Name')),
                ('LName', models.CharField(default=None, max_length=50, verbose_name='Last Name')),
            ],
        ),
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clockin.Intern', verbose_name='User'),
        ),
    ]
