# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0008_auto_20170523_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(13, 31, 3, 414123), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(13, 31, 3, 414157), verbose_name='Time Out'),
        ),
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.CharField(default=None, max_length=50, verbose_name='User'),
        ),
    ]
