# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0009_auto_20170523_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(13, 46, 42, 834277), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(13, 46, 42, 834313), verbose_name='Time Out'),
        ),
    ]
