# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0010_auto_20170523_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='MName',
        ),
        migrations.AddField(
            model_name='intern',
            name='username',
            field=models.CharField(default=None, max_length=50, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='work',
            name='intern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clockin.Intern'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(14, 57, 15, 134772), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(14, 57, 15, 134847), verbose_name='Time Out'),
        ),
    ]
