# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 17:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0011_auto_20170523_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='duration',
            field=models.IntegerField(default=datetime.timedelta(0), verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(13, 20, 38, 407557), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(13, 20, 38, 407594), verbose_name='Time Out'),
        ),
    ]
