# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0012_auto_20170524_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(13, 22, 38, 866620), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(13, 22, 38, 866656), verbose_name='Time Out'),
        ),
    ]
