# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0013_auto_20170524_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(10, 3, 28, 321378), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(10, 3, 28, 321426), verbose_name='Time Out'),
        ),
    ]
