# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0014_auto_20170530_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(10, 10, 27, 632310), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(10, 10, 27, 632310), verbose_name='Time Out'),
        ),
    ]
