# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 14:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0018_auto_20170530_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(10, 24, 32, 400561), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(10, 24, 32, 400561), verbose_name='Time Out'),
        ),
    ]
