# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0019_auto_20170530_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(10, 39, 37, 947102), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(10, 39, 37, 947152), verbose_name='Time Out'),
        ),
    ]
