# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0022_auto_20170824_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(15, 33, 55, 717886), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(15, 33, 55, 717886), verbose_name='Time Out'),
        ),
    ]
