# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 03:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0023_auto_20170904_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(23, 15, 34, 987514), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(23, 15, 34, 987545), verbose_name='Time Out'),
        ),
    ]
