# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0025_auto_20170913_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(13, 45, 19, 749104), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(13, 45, 19, 749133), verbose_name='Time Out'),
        ),
    ]
