# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0026_auto_20170914_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(13, 11, 52, 760876), verbose_name='Time In'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(13, 11, 52, 760876), verbose_name='Time Out'),
        ),
    ]
